spring:
  application:
    name: SoCo Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/soco
    username: ayush
    password: mcd@2023
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update